version: "3.9"

services:
  redis:
    container_name: redis_lesson
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5